name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Install project (editable) with dev extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"

      - name: Lint (ruff)
        run: |
          python -m pip install ruff
          ruff check src

      - name: Run tests (pytest)
        run: |
          python -m pip install pytest
          pytest -q

      - name: Build package
        run: |
          python -m pip install build
          python -m build

      - name: Build docs (MkDocs)
        run: |
          python -m pip install mkdocs mkdocstrings mkdocstrings-python mkdocs-material pymdown-extensions
          mkdocs build --site-dir site
