name: Deploy Docs to GitHub Pages (official)

on:
  push:
    branches: [ master, main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocstrings mkdocstrings-python mkdocs-material pymdown-extensions
          # Install the project in editable mode so mkdocstrings can import it
          python -m pip install -e ".[dev]"

      - name: Build MkDocs site
        run: mkdocs build --site-dir site

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: site

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
          publish_dir: ./site
